### ISSUE TITLE
Corrupts downloads and instantly disconnects

### ISSUE THREAD

**Issue by m4x10187** [Team-Resurgent/Pandora#5]
I've been trying to download some Xbox files, and upon doing so, downloads end up being 0 bytes and doesn't show the progress of my download. After a while, when left idle, it instantly disconnects from the XBINS server.

**Comment by HoRnEyDvL** [comment]
Can you confirm that windows or your firewall is not blocking / deleting your download.

As for the disconnects , Xbins kicks you off  after x period of time that is expected behavior and out of our control sorry.
